name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: JLJDXJH/JLJDXJH.github.io
          BRANCH: gh-pages
          CNAME: blog.jljdxjh.top

